version: '3'
services:
  collector:
    build: collector/
    command: ruby collect.rb blocks
    volumes:
      - ./collector:/myapp

  estimator:
    build: estimator/
    command: python --version
    volumes:
      - ./estimator:/myapp
    depends_on:
      - collector
  api:
    build: api/
    command: flask run
    environment:
      - FLASK_APP=app.py
    ports:
      - "3000:5000"
    volumes:
      - ./api:/myapp
      - ./estimator:/estimator
    depends_on:
      - estimator
