version: '3'
services:

  collector:
    build: collector/
    command: ruby collect.rb blocks
    volumes:
      - ./collector:/myapp

  estimator:
    build: estimator/
    command: python --version
    volumes:
      - ./estimator:/myapp
    depends_on:
      - collector

  # api:
    # build: api/
    # command: flask run -h 0.0.0.0
    # environment:
      # - FLASK_APP=app.py
    # ports:
      # - "5000:5000"
    # volumes:
      # - ./api:/myapp
      # - ./estimator:/estimator
    # depends_on:
      # - estimator
